### ISSUE TITLE
How to use advanced API's

### ISSUE THREAD

**Issue by libin85** [roubachof/Xamarin.Forms.Nuke#10]
How do I use the Nuke API when using this binding library? Do you have any sample project that I can use as a refernce. I would like have a placeholder image, and I can see we can do that using Nuke API. https://www.raywenderlich.com/9229-nuke-tutorial-for-ios-getting-started#toc-anchor-004

**Comment by roubachof** [comment]
Since Nuke is just an ImageSourceHandler for Xamarin.Forms, the api provided is the XF api.
