### ISSUE TITLE
Use Nuke for UriImageSource only (remove FileImageSource)

### ISSUE THREAD

**Issue by spidei** [roubachof/Xamarin.Forms.Nuke#13]
Proposal:

Xamarin.Forms.Nuke is an amazing library, and works awesome with UriImageSource, but has some problems with FileImageSource like seen on issues #11 and #9. If the resources are on the Resources folder and manage resolution using three images for each one (for example add_photo.png, add_photo@2x.png and add_photo@3x.png), on high density devices Images are blurred and Buttons with image shows the smallest image. On attached image you will see both issues: on left side loaded with Xamarin.Forms.Nuke and on right side with the library modified to use UriImageSource only.

![Nuke-compare](https://user-images.githubusercontent.com/26327444/96842673-9cc31500-144d-11eb-8cad-2e7d23a90808.png)

Fixing this issues is not simple, based on [ffimageloading code](https://github.com/luberda-molinet/FFImageLoading/blob/master/source/FFImageLoading.Shared.IosMac/DataResolvers/BundleDataResolver.cs), and if finally most of the resources will be load using UIImage.FromBundle (as seen on #5), why don't be simple and use Nuke only for UriImageSource? It will work great on caching and managing url images, and resources will be managed as usual.

Also, Glidex works for UriImageSource only 👍

**Comment by roubachof** [comment]
Yup. 
But since it caches and handles way better file image than the default one (50% memory), I still want to support this case. 
I won't support adding different density images in the Resources folder since it is a deprecated way to deal with images.
Starting with iOS 9, you should use Asset Catalogs Image Sets: 
https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/displaying-an-image?tabs=macos

However I will add a configuration option to disable the handling of such source in the next version :)

**Comment by spidei** [comment]
Wow! A configuration option will be awesome! Thank you!

Meanwhile, I will investigate how to migrate into Asset Catalogs 😅

**Comment by roubachof** [comment]
Ok I think I talked some nonsense here.
I am currently investigating this, and it seems that if you are using xcasset, you can't get around the native caching of images.
It means you can't get the URI of the image matching your density.
So in fact Nuke will never work with Asset catalog (I dunno why I assumed it would, silly me :).
But it might work with the deprecated way of doing it since I can add @2x, @3x automatically depending on the scale returned.
But anyway, I will add the option to disable it just in case.

**Comment by roubachof** [comment]
Yup, Nuke will be able to cache images ONLY when using the good old fashion way x)
So your issue will be fixed: you don't have to move anything around.
Anyway, with the next fix, it should also work if your put images in the Asset Catalog, it will just use the native cache in this case.

**Comment by spidei** [comment]
Great! If you want I can test the fix on a huge App with lots of images on Resources folder :) 

Thanks!

**Comment by roubachof** [comment]
that's the plan, will post a pre release here to be tested :)

**Comment by roubachof** [comment]
Here we go.
Please @spidei @acuntex @libin85 test this pre release package see if it fixes your `FileImageSource` issues.

[Xamarin.Forms.Nuke.8.4.1-pre1.nupkg.zip](https://github.com/roubachof/Xamarin.Forms.Nuke/files/5423147/Xamarin.Forms.Nuke.8.4.1-pre1.nupkg.zip)

**Comment by spidei** [comment]
Wow! 8.4.1 works great with Resources folder! Great work!

Suggestion: It will be great if HandleFileSourceAsync not only look for the current density image, also try to find for closest density. For example, if @3 file don't exists, try to use the @2 density, or @1. In most all cases, it will find the correct file at the first attempt, and if the resource exists, will always find a resource, even if is on a smaller resolution.
Something like:

```
if (!Path.HasExtension(fileName))
{
	FormsHandler.Debug(() => $"Image without extension: loading \"{fileName}\" from Bundle");
	return Task.FromResult(UIImage.FromBundle(fileName));
}
else
{
	string name = Path.GetFileNameWithoutExtension(fileName);
	NSUrl fileUrl = null;

	for (float currentScale = scale; currentScale >= 1; currentScale--)
	{
		string nameWithSuffix = $"{name}{ScaleToDensitySuffix[currentScale]}";
		string filenameWithDensity = fileName.Replace(name, nameWithSuffix);
		if (File.Exists(filenameWithDensity))
		{
			FormsHandler.Debug(() => $"Loading \"{filenameWithDensity}\" as a file URI");
			fileUrl = NSUrl.FromFilename(filenameWithDensity);
			break;
		}
	}

	if (fileUrl != null)
		return LoadImageAsync(fileUrl);
	else
	{
		FormsHandler.Debug(() => $"Couldn't retrieve the image URI: loading \"{fileName}\" from Bundle");
		return Task.FromResult(UIImage.FromBundle(fileName));
	}
}
```

**Comment by roubachof** [comment]
yeah I get the idea but I won't do that :)
I don't want user that name correctly their local resources to get a performance hit to take care of lazy dev x)

**Comment by spidei** [comment]
Ok, fair enough :D

Thanks for the new version fix! Works like a charm :)

**Comment by acuntex** [comment]
@roubachof Thank you very much!

I was finally able to replace FFImageLoading, which was responsible for a lot of problems in my App!

When are you going to upload the new version to nuget.org (even as prerelease)? I just don't want to put too many unnecessary binary assets in my git repository.

**Comment by roubachof** [comment]
Glad it solved your issue ! It will be released Monday

**Comment by roubachof** [comment]
fixed by https://github.com/roubachof/Xamarin.Forms.Nuke/releases/tag/v8.4.1
