### ISSUE TITLE
The SwiftSupport folder is missing

### ISSUE THREAD

**Issue by Alex-Dobrynin** [roubachof/Xamarin.Forms.Nuke#15]
After updating nuke to version 8.4.1 i got next error :
![image](https://user-images.githubusercontent.com/23138430/97322809-d5615500-1878-11eb-9659-a415df3fe663.png)

please, try to use smth else instead of
![image](https://user-images.githubusercontent.com/23138430/97323038-0d689800-1879-11eb-8085-0ad155a51533.png)

**Comment by roubachof** [comment]
I can't it's the only runtime support from Xamarin....

**Comment by Alex-Dobrynin** [comment]
> I can't it's the only runtime support from Xamarin....

so then we don`t need functionality to cache resource files.

Also, I noticed that size of ipa increased from 100 to 150 MB with 8.4.1 version

**Comment by roubachof** [comment]
It has nothing to do with resources files, just swift support for iOS < 12.2.
Increased size is due to swift support runtime being added.

**Comment by Alex-Dobrynin** [comment]
> It has nothing to do with resources files, just swift support for iOS < 12.2.
> Increased size is due to swift support runtime being added.

ios < 12 use less then 1% of devices, i don`t think you should even think about them, especially add support for those devices

**Comment by roubachof** [comment]
fair enough, you won x)

**Comment by roubachof** [comment]
The dependency to swift runtime has been removed in 8.4.2.
Seems to be fair that people wanted to support iOS < 12.2 should manually add the package in their target project.
Doing so, we don't penalize user that only want support for 12.2+.
