### ISSUE TITLE
Xamarin.Forms.Nuke.FormsHandler.Init() breaks Plugin.Badge

### ISSUE THREAD

**Issue by acuntex** [roubachof/Xamarin.Forms.Nuke#16]
## 🐛 Bug Report

When using Plugin.Badge in combination with Xamarin.Forms.Nuke.FormsHandler.Init(), the Badges are not shown. Only after changing the values of the badges, they are shown.

### Expected behavior
Plugin.Badge works together with Xamarin.Forms.Nuke.FormsHandler.Init()

### Reproduction steps
1. Install Plugin.Badge
2. Install Xamarin.Forms.Nuke
3. Call Xamarin.Forms.Nuke.FormsHandler.Init()
4. Try to use Badges

See repro: https://github.com/acuntex/NukePluginBadge_Bug

### Configuration

**Version:** 8.4.1

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by acuntex** [comment]
Using `Xamarin.Forms.Nuke.FormsHandler.Init(disableFileImageSourceHandling: true);` makes it work btw.

**Comment by roubachof** [comment]
Well I tried the sample, and all is working fine on Nuke side.
All URI (icon.png) are correctly resolved.
Maybe the author the plugin is using some hacks to display badges on iOS...
I don't know.
So you can use the disableFileImageSourceHandling parameter then.

**Comment by acuntex** [comment]
Thanks, it is weird indeed an makes no sense.

I'll open a bug at the plugin author, thanks!
