### ISSUE TITLE
Gif not works on iOS

### ISSUE THREAD

**Issue by Midnayt** [roubachof/Xamarin.Forms.Nuke#17]
When using
Xamarin.Forms.Nuke.FormsHandler.Init(debug: true, disableFileImageSourceHandling: true);
or
Xamarin.Forms.Nuke.FormsHandler.Init(debug: true, disableFileImageSourceHandling: false);
gif doesn't animates.
But without Nuke initialization works as expected.

**Comment by roubachof** [comment]
I would need a repro sample please.

**Comment by Midnayt** [comment]
[ImageGif.zip](https://github.com/roubachof/Xamarin.Forms.Nuke/files/5458985/ImageGif.zip)
Try this

> I would need a repro sample please.

**Comment by roubachof** [comment]
Thank you for the repro :)
Found the issue, will be fixed in 8.4.3
