### ISSUE TITLE
Image.Source pointing to PDF vector images are no longer drawn

### ISSUE THREAD

**Issue by gsgou** [roubachof/Xamarin.Forms.Nuke#3]
using XF 4.4.0.991864
the corresponding UIImage is null by adding the lib in this case

**Comment by roubachof** [comment]
More info please

**Comment by NunoBem** [comment]
> More info please

@roubachof I just migrated to Nuke and GlideX for my iOS and Android app from FFImageLoading. I only have a couple images in the projects assets and are all vector (xml in Android and pdf in iOS). In FFImageLoading all worked, after migrating, Android works but not iOS. Gives the follow error:

Debug Output:
2020-04-10 14:55:45.575 ToGuests.iOS[617:320379] 04-10 14:55:45.575|Nuke|WNG:	Unexpected exception in FFImageLoading image source handler: System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Forms.Nuke.NukeHelper.LoadViaNuke (Xamarin.Forms.ImageSource source, System.Threading.CancellationToken token) [0x00159] in D:\Dev\Sharpnado\src\Xamarin.Forms.Nuke\Xamarin.Forms.Nuke\NukeHelper.cs:60 

XAML:
`                    <Image WidthRequest="400"
                           HeightRequest="200"
                           Margin="30"
                           HorizontalOptions="CenterAndExpand"
                           VerticalOptions="CenterAndExpand"
                           Aspect="AspectFit"
                           Source="logo_toguests" />`

Nuggets:
Xamarin Forms 4.4.0.991864
Xamarin.Forms.Nuke 8.4.0

iOS Assets:
![image](https://user-images.githubusercontent.com/524734/79000726-b00b3480-7b3c-11ea-9361-233674b3c484.png)

**Comment by roubachof** [comment]
ty for the PR, will merge it after binding version 9.0 :)

**Comment by NunoBem** [comment]
> ty for the PR, will merge it after binding version 9.0 :)

Hey @roubachof ! Is there an ETA for the 9.0 release? Thanks in advance!

**Comment by roubachof** [comment]
9.1 will come this month, after I release my next big XF component ;)

**Comment by roubachof** [comment]
fixed by v8.4.1
