### ISSUE TITLE
Tab bar icons disappear when adding Nuke

### ISSUE THREAD

**Issue by libin85** [roubachof/Xamarin.Forms.Nuke#9]
Hi Jean, 

Appreciate your effort in creating this library. I was trying to use Nuke in one of project, and I have identified an issue. If I include Nuke in my project, my tabbar icons disappear. Is this a known issue? Any workarounds or fixes available?

I also see a similar issue raised here https://forums.xamarin.com/discussion/181348/hamburger-menu-replace-with-text-with-xamarin-forms-nuke

**Comment by roubachof** [comment]
It's possibly related to #13. I will add a quickfix, a release will be done this week or the next one :)
